$lines = @(
'@echo off',
'setlocal enabledelayedexpansion',
'set WAR=%1',
'set INSTANCIA=%2',
'set WILDFLY_HOME=C:\wildfly-39.0.1.Final',
'if "%WAR%"=="" ( echo [ERROR] Indica el nombre del WAR && exit /b 1 )',
'if "%INSTANCIA%"=="" set INSTANCIA=1',
'if "%INSTANCIA%"=="1" set DEPLOY_DIR=!WILDFLY_HOME!\standalone\deployments',
'if "%INSTANCIA%"=="1" set PUERTO=8080',
'if "%INSTANCIA%"=="2" set DEPLOY_DIR=!WILDFLY_HOME!\standalone2\deployments',
'if "%INSTANCIA%"=="2" set PUERTO=8180',
'if not exist "!DEPLOY_DIR!\!WAR!" ( echo [ERROR] No existe !WAR! en !DEPLOY_DIR! && exit /b 1 )',
'echo.',
'echo [INFO]  Instancia   : !INSTANCIA! (puerto !PUERTO!)',
'echo [INFO]  WAR         : !WAR!',
'echo [INFO]  Carpeta     : !DEPLOY_DIR!',
'echo.',
'echo [INFO]  Creando .dodeploy...',
'echo. > "!DEPLOY_DIR!\!WAR!.dodeploy"',
'echo [INFO]  .dodeploy creado OK',
'echo.',
'echo [INFO]  Esperando despliegue...',
'set CONTADOR=0',
':WAIT_LOOP',
'timeout /t 2 /nobreak >nul',
'set /a CONTADOR+=2',
'if exist "!DEPLOY_DIR!\!WAR!.deployed" goto SUCCESS',
'if exist "!DEPLOY_DIR!\!WAR!.failed"   goto FAILED',
'if !CONTADOR! geq 60 goto TIMEOUT',
'goto WAIT_LOOP',
':SUCCESS',
'echo.',
'echo [OK]    Desplegado en !CONTADOR!s',
'echo [OK]    URL: http://127.0.0.1:!PUERTO!/!WAR:.war=!/',
'echo !date! !time! OK !WAR! inst!INSTANCIA! >> "!WILDFLY_HOME!\deploy-history.log"',
'echo [LOG]   Registrado en deploy-history.log',
'goto END',
':FAILED',
'echo.',
'echo [ERROR] Despliegue fallido en !CONTADOR!s',
'echo [ERROR] Revisa: !DEPLOY_DIR!\!WAR!.failed',
'echo !date! !time! FAILED !WAR! inst!INSTANCIA! >> "!WILDFLY_HOME!\deploy-history.log"',
'goto END',
':TIMEOUT',
'echo.',
'echo [ERROR] Timeout - no respondio en 60s',
'echo !date! !time! TIMEOUT !WAR! inst!INSTANCIA! >> "!WILDFLY_HOME!\deploy-history.log"',
'goto END',
':END',
'endlocal'
)

$lines | Out-File -FilePath "C:\wildfly-39.0.1.Final\bin\deploy.bat" -Encoding ASCII
